apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hamid-cni.fullname" . }}-cni
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hamid-cni.labels" . | nindent 4 }}
data:
  {{ .Values.cni.confName }}: |
    {
      "cniVersion": "1.0.0",
      "name": {{ .Values.cni.netName | quote }},
      "plugins": [
        {
          "type": "loopback"
        },
        {
          "type": "hamid-cni",
          "socketPath": {{ .Values.cni.socketPath | quote }},
          "mtu": {{ .Values.cni.mtu }}
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          },
          "snat": true
        }
      ]
    }
